### ISSUE TITLE
Add XMLReader as a requirement

### ISSUE THREAD

**Issue by notoriousturtle** [AsperaGmbH/xlsx-reader#1]
Under 'Requirements' in the README.md add XMLReader.

**Comment by rfischer42** [comment]
Greetings notoriousturtle,

Thank you for your report. The XMLReader requirement was indeed missing from the description.

As such, this commit includes an adjustment of the README.md file that adds XMLReader to the requirements list: https://github.com/AsperaGmbH/xlsx-reader/commit/cb3cfbd25eb01a991226fa1948d3e45f54d9097e

Sincerely - René Fischer
