### ISSUE TITLE
Reader incorrectly handles empty <row> elements

### ISSUE THREAD

**Issue by ralfstrobel** [AsperaGmbH/xlsx-reader#10]
We encountered an XLSX file with sheet data in the following form:
```xml
<row r="1" spans="1:9" ht="15.75" thickBot="1" x14ac:dyDescent="0.3"/>
<row r="2" spans="1:9" x14ac:dyDescent="0.25">
	<c r="A2" s="3" t="s">
		<v>0</v>
	</c>
	...
</row>
```
Note how the first `<row>` element merely consists of a self-closing tag.

This is currently not handled correctly by the Reader, which only checks `$this->worksheet_reader->isClosingTag()` to detect the end of a row. The worksheet_reader would also have to consider the state of `$this->isEmptyElement`.

The result is that the Reader keeps reading forward until it reaches the `</row>` tag of row 2, incorrectly reading and outputting the cells of row 2 as the content of row 1. Then it returns empty values for row 2, since there are no further cells to be read.

**Comment by rfischer42** [comment]
Hey there!

Thank you for the detailed report. It made reproduction of the issue very straightforward.
Your suggestion for a fix was also entirely correct. : )

As such, there's now a new release available which should fix the issue. Please check it out.

**Comment by ralfstrobel** [comment]
Thank you for the quick fix! I can confirm that the Reader is now able to read the problematic file we encountered correctly.

Sorry if I am getting greedy, but I'm going to open another issue regarding one more minor problem we encountered while testing your library. That one should hopefully be a bit easier.
