### ISSUE TITLE
Error open XLS

### ISSUE THREAD

**Issue by fmoreno-intercom** [AsperaGmbH/xlsx-reader#13]
I try to open this XLS from de URL location [Año 2021, Trimestre IV](http://www.bcv.org.ve/sites/default/files/EstadisticasGeneral/2_1_2d21_otrasmonedas.xls) but all the time lauch a error. How can fix or debug the problem

**Comment by DerKuehneKollege** [comment]
The library unfortunately only supports XLS**X** files (the modern format), not the deprecated XLS format.
