### ISSUE TITLE
Is it possible to force the library to ignore all the data types that XLSX ..?

### ISSUE THREAD

**Issue by EOM** [AsperaGmbH/xlsx-reader#20]
Hi, very good library, it works very well.
My question is, is it possible to force the library to ignore all the data types that XLSX has, so that all the cells are taken as a literal string, regardless of whether it was saved as a date, currency, decimal, etc.
Since I did not find a way to do it.
Thanks

**Comment by rfischer42** [comment]
Greetings,

First off: No, this is not an option right now.

The main reason for it is that XLSX file editors generally like storing everything as a number internally; even including strings.
So while the reader *could* just hand you the raw cell value "42", that wouldn't really tell you anything without any further context. "42" could mean "The string with the id 42, which is 'Hello World'", or it could mean "the datetime corresponding to 42, which is 1900-02-11 00:00:00", or it could actually just be the number 42. So it always seemed ill-advised to allow outputting the raw value like that.

Maybe it'd help if you described your use-case. What are you trying to accomplish?

**Comment by rfischer42** [comment]
Closing due to missing response; Assuming that the issue has been resolved via another route.
