### ISSUE TITLE
Error "P-1D" when reading an incorrect DateTime

### ISSUE THREAD

**Issue by drasill** [AsperaGmbH/xlsx-reader#3]
Hi,

I have a document where the date seems to be `-1`, probably because of an export.

The Excel file is opened in libreoffice, where the date appears as "29/12/1899".

But the reader throws an Exception when stumbling on this value :
`Exception with message 'DateInterval::__construct(): Unknown or bad format (P-1D)'`.

**Comment by drasill** [comment]
Thank you for the merge !

Would you release a new version too, please ?

**Comment by rfischer42** [comment]
Sure thing!
