### ISSUE TITLE
Is there anyway to get the "value" from a cell (unformatted)

### ISSUE THREAD

**Issue by AzzaAzza69** [AsperaGmbH/xlsx-reader#5]
eg.
  -12345.67 for a number formatted _(£#,##0_);(£#,##0)
as I get "(12,345.67)"?

**Comment by rfischer42** [comment]
Hello Azza,

No, currently there is no such functionality. Values are always output with formatting applied.

**Comment by rfischer42** [comment]
... except now there *is* such functionality. : )

When instantiating the Reader, you can now set the 'ReturnUnformatted' configuration setting to true in order to retrieve values without formatting applied.
