### ISSUE TITLE
Problem handling Currency with Symbol £ English (United Kingdom)

### ISSUE THREAD

**Issue by AzzaAzza69** [AsperaGmbH/xlsx-reader#6]
The value "170.00" formatted as Currency / Symbol £
is coming out as fine as "170.00"

but the value "" formatted as Currency / Symbol £ English (United Kingdom)
is commng out as "-Â£170.00"

**Comment by rfischer42** [comment]
Hello Azza,

Unfortunately, I cannot entirely reproduce this issue on my end.
Can you upload an XLSX file that causes this problem?

**Comment by rfischer42** [comment]
Alternatively, check with the new version that was just published. As that includes a rather substantial rewrite of the number format parser, it might have changed the behavior in regards to your issue as well.
