### ISSUE TITLE
Handling invalid row spans values?

### ISSUE THREAD

**Issue by gRoberts84** [AsperaGmbH/xlsx-reader#9]
Hi there,

I am using `xslx-reader` to parse a customer provided spreadsheet and it has handled their horror of a document with little drama however when trying to parse a particular sheet, it reaches a standard line and then throws an exception.

```
A non well formed numeric value encountered 
  at vendor/aspera/xlsx-reader/lib/Reader.php:296
```

After tracking this down, the spans value was `1:7167 7169:14335 14337:16379`. 

I'm unable to modify the spreadsheet and visually inspecting it doesn't appear to show any reason for this within Excel?

Is there anything that can be done via the code to gracefully handle this and move on to the next row? 

Thanks

**Comment by rfischer42** [comment]
Greetings,

Thank you for the detailed report, it made reproducing the problem very straightforward.
There's a new version available now that should fix the issue. Please check if this also solves the problems you're experiencing in your case.

In either case, I wish you best of luck with that document over there. : )

**Comment by gRoberts84** [comment]
> Greetings,
> 
> Thank you for the detailed report, it made reproducing the problem very straightforward.
> There's a new version available now that should fix the issue. Please check if this also solves the problems you're experiencing in your case.
> 
> In either case, I wish you best of luck with that document over there. : )

Hi @adirfische , 

Thank you for looking into this! 

Can confirm that everything is working properly now! 

Thanks again
